CREATE TABLE IF NOT EXISTS project_imports (
  id TEXT PRIMARY KEY,
  project_code TEXT NOT NULL,
  source_file TEXT NOT NULL,
  expected_rows INTEGER NOT NULL CHECK (expected_rows BETWEEN 1 AND 50000),
  next_row INTEGER NOT NULL DEFAULT 0,
  committed INTEGER NOT NULL DEFAULT 0 CHECK (committed IN (0, 1, 2)),
  commit_token TEXT,
  expires_at INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_project_imports_expiry ON project_imports(expires_at);

CREATE TABLE IF NOT EXISTS project_progress_import_rows (
  import_id TEXT NOT NULL REFERENCES project_imports(id) ON DELETE CASCADE,
  row_index INTEGER NOT NULL,
  source_row INTEGER NOT NULL,
  item TEXT,
  mh TEXT,
  wo_date TEXT,
  product_type TEXT,
  classification TEXT,
  allocation TEXT,
  drawing TEXT,
  part_no TEXT,
  size TEXT,
  quantity REAL,
  unit_weight REAL,
  total_weight REAL,
  profile TEXT,
  item_id TEXT,
  note TEXT,
  fitup_date TEXT,
  fitup_qty REAL,
  fitup_weight REAL,
  welding_date TEXT,
  welding_qty REAL,
  welding_weight REAL,
  trial_assembly_date TEXT,
  trial_assembly_qty REAL,
  trial_assembly_weight REAL,
  acceptance_date TEXT,
  acceptance_qty REAL,
  acceptance_weight REAL,
  handover_date TEXT,
  handover_qty REAL,
  handover_weight REAL,
  receiver TEXT,
  record_no TEXT,
  PRIMARY KEY (import_id, row_index)
);
