CREATE TABLE IF NOT EXISTS public.projects (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  source_file TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'viewer')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sessions (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON public.sessions(expires_at);

CREATE TABLE IF NOT EXISTS public.materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code TEXT NOT NULL REFERENCES public.projects(code) ON DELETE CASCADE,
  source_file TEXT NOT NULL,
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  drawing TEXT,
  assembly TEXT,
  description TEXT,
  part_no TEXT,
  size TEXT,
  scope TEXT,
  quantity DOUBLE PRECISION,
  weight DOUBLE PRECISION,
  received DOUBLE PRECISION,
  remaining DOUBLE PRECISION,
  as_symbol TEXT,
  delivery_date TEXT,
  issue_dates TEXT,
  is_main SMALLINT NOT NULL DEFAULT 0,
  parent TEXT,
  status TEXT NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_materials_project ON public.materials(project_code);
CREATE INDEX IF NOT EXISTS idx_materials_parent ON public.materials(project_code, source_file, source_sheet, is_main);

CREATE TABLE IF NOT EXISTS public.project_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code TEXT NOT NULL REFERENCES public.projects(code) ON DELETE CASCADE,
  source_file TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  item TEXT,
  mh TEXT,
  wo_date TEXT,
  product_type TEXT,
  classification TEXT,
  allocation TEXT,
  drawing TEXT,
  part_no TEXT,
  size TEXT,
  quantity DOUBLE PRECISION,
  unit_weight DOUBLE PRECISION,
  total_weight DOUBLE PRECISION,
  profile TEXT,
  item_id TEXT,
  note TEXT,
  monthly_plan TEXT,
  material_received_percent DOUBLE PRECISION,
  material_received_weight DOUBLE PRECISION,
  fitup_date TEXT,
  fitup_qty DOUBLE PRECISION,
  fitup_weight DOUBLE PRECISION,
  welding_date TEXT,
  welding_qty DOUBLE PRECISION,
  welding_weight DOUBLE PRECISION,
  trial_assembly_date TEXT,
  trial_assembly_qty DOUBLE PRECISION,
  trial_assembly_weight DOUBLE PRECISION,
  acceptance_date TEXT,
  acceptance_qty DOUBLE PRECISION,
  acceptance_weight DOUBLE PRECISION,
  handover_date TEXT,
  handover_qty DOUBLE PRECISION,
  handover_weight DOUBLE PRECISION,
  receiver TEXT,
  record_no TEXT,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_progress_project ON public.project_progress(project_code);
CREATE INDEX IF NOT EXISTS idx_progress_drawing ON public.project_progress(project_code, drawing);

CREATE TABLE IF NOT EXISTS public.import_runs (
  id TEXT PRIMARY KEY,
  project_code TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('materials', 'projects', 'btp')),
  source_file TEXT NOT NULL,
  imported_rows INTEGER NOT NULL DEFAULT 0,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.material_imports (
  id TEXT PRIMARY KEY,
  project_code TEXT NOT NULL,
  source_file TEXT NOT NULL,
  expected_rows INTEGER NOT NULL CHECK (expected_rows BETWEEN 1 AND 50000),
  next_row INTEGER NOT NULL DEFAULT 0,
  committed SMALLINT NOT NULL DEFAULT 0 CHECK (committed IN (0, 1, 2)),
  commit_token TEXT,
  expires_at BIGINT NOT NULL,
  category TEXT NOT NULL DEFAULT 'materials' CHECK (category IN ('materials', 'btp')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_material_imports_expiry ON public.material_imports(expires_at);

CREATE TABLE IF NOT EXISTS public.material_import_rows (
  import_id TEXT NOT NULL REFERENCES public.material_imports(id) ON DELETE CASCADE,
  row_index INTEGER NOT NULL,
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  drawing TEXT,
  assembly TEXT,
  description TEXT,
  part_no TEXT,
  size TEXT,
  scope TEXT,
  quantity DOUBLE PRECISION,
  weight DOUBLE PRECISION,
  received DOUBLE PRECISION,
  remaining DOUBLE PRECISION,
  as_symbol TEXT,
  delivery_date TEXT,
  issue_dates TEXT,
  is_main SMALLINT NOT NULL DEFAULT 0,
  parent TEXT,
  status TEXT NOT NULL,
  PRIMARY KEY (import_id, row_index)
);

CREATE TABLE IF NOT EXISTS public.btp_material_import_rows (
  import_id TEXT NOT NULL REFERENCES public.material_imports(id) ON DELETE CASCADE,
  row_index INTEGER NOT NULL,
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  part_no TEXT,
  material_type TEXT,
  description TEXT,
  material TEXT,
  unit TEXT,
  size TEXT,
  length_mm DOUBLE PRECISION,
  unit_weight DOUBLE PRECISION,
  total_weight DOUBLE PRECISION,
  design_quantity DOUBLE PRECISION,
  received DOUBLE PRECISION,
  remaining DOUBLE PRECISION,
  daily_progress TEXT,
  joint_check TEXT,
  status TEXT,
  note TEXT,
  PRIMARY KEY (import_id, row_index)
);

CREATE TABLE IF NOT EXISTS public.btp_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code TEXT NOT NULL REFERENCES public.projects(code) ON DELETE CASCADE,
  source_file TEXT NOT NULL,
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  part_no TEXT,
  material_type TEXT,
  description TEXT,
  material TEXT,
  unit TEXT,
  size TEXT,
  length_mm DOUBLE PRECISION,
  unit_weight DOUBLE PRECISION,
  total_weight DOUBLE PRECISION,
  design_quantity DOUBLE PRECISION,
  received DOUBLE PRECISION,
  remaining DOUBLE PRECISION,
  daily_progress TEXT,
  joint_check TEXT,
  status TEXT,
  note TEXT,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_btp_materials_project ON public.btp_materials(project_code, source_file, source_sheet, source_row);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_import_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.btp_material_import_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.btp_materials ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.projects, public.users, public.sessions, public.materials,
  public.project_progress, public.import_runs, public.material_imports,
  public.material_import_rows, public.btp_material_import_rows, public.btp_materials
  FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
